### ISSUE TITLE
Not working on category archives

### ISSUE THREAD

**Issue by judge** [woothemes/woosidebars#20]
I created a sidebar which shows on a specific category archive and 'all posts' on specified category. It works on single posts, but it does not on category archives.
After digging in the queries, I found this:
On single posts, the query is fine, and the correct sidebar is shown:

``` sql
SELECT   wp_posts.ID FROM wp_posts  INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id)
INNER JOIN wp_postmeta AS mt1 ON (wp_posts.ID = mt1.post_id) WHERE 1=1  AND wp_posts.post_type = 'sidebar' AND (wp_posts.post_status = 'publish') AND ( (wp_postmeta.meta_key = '_sidebar_to_replace' AND CAST(wp_postmeta.meta_value AS CHAR) != '')
AND  (mt1.meta_key = '_condition' AND CAST(mt1.meta_value AS CHAR) IN ('post-18838','in-term-6','post','post-type-post','single','singular')) ) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 200
```

But on category archives, the query is the following:

``` sql
SELECT   wp_posts.ID FROM wp_posts  INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id)
INNER JOIN wp_postmeta AS mt1 ON (wp_posts.ID = mt1.post_id) WHERE 1=1  AND wp_posts.post_type IN ('post', 'interview', 'nav_menu_item') AND (wp_posts.post_status = 'publish') AND ( (wp_postmeta.meta_key = '_sidebar_to_replace' AND CAST(wp_postmeta.meta_value AS CHAR) != '')
AND  (mt1.meta_key = '_condition' AND CAST(mt1.meta_value AS CHAR) IN ('term-6','archive-category','archive')) ) GROUP BY wp_posts.ID ORDER BY wp_posts.post_date DESC LIMIT 0, 200
```

The problematic part is the post_type, it seems that get_posts (class-woo-widebar.php, line 523) ignores post_type in its $args, but only on category archives.

Any idea why is this happening?

**Comment by dnwst** [comment]
I know it's one year down the road, but @mattyza I've run into the same issue, although I don't see the issue when I'm logged in as admin.

Custom sidebars display fine on single posts in a certain category, but it's not displaying in the category pages. There it just shows the default sidebar. It does show the correct custom sidebar if I'm logged in as admin.

I don't have any caching plugin on my test site so that can't be the issue. Here's the website:

http://demo.earlytorise.com/

Any idea why it's only working when I'm logged in and not for regular visitors?

**Comment by mattyza** [comment]
Hi @dnwst.

Could you please advise a screenshot of the category conditions you've set up for the sidebar in question?

**Comment by dnwst** [comment]
Sure, see below. The only thing I have selected is the "Health" category under Taxonomy Terms. On a side note, as you can see in the other screenshot I had trouble deselecting the other taxonomy terms when trying to troubleshoot this, but I see that's another open bug.

![category-options](https://cloud.githubusercontent.com/assets/2295700/6098149/0adf64c2-afd6-11e4-83ec-be4925fd3fac.jpg)
![widget_areas](https://cloud.githubusercontent.com/assets/2295700/6098150/0c86e55c-afd6-11e4-9bb8-d41d446c0b8f.jpg)

Below is a link to the category page where the custom sidebar should be displayed, but instead the default sidebar is displayed (although as mentioned the custom sidebar is displaying correctly for me when I'm logged in as admin):

http://www.earlytorise.com/issues/etr-health/

**Comment by mattyza** [comment]
@dnwst - Could I ask you to email me your WordPress login credentials for this, please? matt at woothemes dot com.

I suspect there is potentially a duplicate slug issue happening here and would like to confirm before posting that we've resolved this.

**Comment by dnwst** [comment]
@mattyza I've emailed you credentials. I did check the widget area slugs and didn't find any duplicates, but maybe I looked in the wrong place.

**Comment by mattyza** [comment]
@dnwst It looks, to me, like the issue stems from how your theme is calling it's sidebars. It's calling `sidebar-1` and `sidebar-2` inside `sidebar.php`. WordPress, by default, calls sidebars with `sidebar-*` where the number is whichever sidebar is being registered at that index in the system. Thus, there could be `sidebar-10`, for example. This number is dynamic.

I'd advise adjusting the theme to declare sidebars with a dedicated name for each, for example `primary` and `secondary` or whichever is appropriate.

This should resolve compatibility with WooSidebars. :)

**Comment by dnwst** [comment]
Thanks for looking into it. I tried this though and still see the same issue.

`sidebar-1` and `sidebar-2` are registered in functions.php using `register_sidebar` so they're fixed IDs. I'm not sure how changing them to e.g. `primary-sidebar` and `secondary-sidebar` in `functions.php` and `sidebar.php` would change anything. Let me know if you think I missed something.

The question remains though as to why WooSidebars is showing the correct categories on archive pages when I'm logged in as admin, but not for regular visitors. Is there a difference in how WooSidebars decides which sidebar to show for admins vs. non admins?

The only thing that stood out to me in the code (I'm not a programmer by any means) is this:
`	public function replace_sidebars ( $sidebars_widgets ) {
		if ( is_admin() ) {
	 		return $sidebars_widgets;
	 	} ...`

**Comment by mattyza** [comment]
@dnwst - That snippet is such that sidebar widgets aren't replaced in the admin view of WordPress. :)

I'd suggest making a clone of your website on a staging server, deactivating all other plugins and seeing if that helps. I feel there may be a plugin or server conflict at play, here, as this is the first I've seen of this.

**Comment by dnwst** [comment]
@mattyza I finally figured out the issue! It wasn't a plugin or the theme.

We use a custom post type on our website, and to get archive pages to display the custom post type along with regular posts we've had to include this code in `functions.php`:

-----------------
function add_custom_types_to_tax( $query ) {
if( is_category() || is_tag() && empty( $query->query_vars['suppress_filters'] ) ) {

// Get your post types
$post_types = array( 'post', 'our-custom-post-type-name' );

$query->set( 'post_type', $post_types );
return $query;
}
}
add_filter( 'pre_get_posts', 'add_custom_types_to_tax' );
-----------------

For starters I've limited the function to only apply to the category with our custom post type, so that has fixed 90% of the issue. This way of showing custom post types on archive pages somehow conflicts with WooSidebars though. I'll have to see how I can find a workaround or pinpoint the specific issue.

**Comment by mattyza** [comment]
@dnwst - Would be interested to hear your resolution, once you've found it.

I'd say, try running `wp_reset_query();` before calling your sidebars. That should restore the query to it's original state.

Other than that, you could try setting a different condition for your sidebar, based on how you've modified the query.
