### ISSUE TITLE
Widgets added to a Widget Area disappear after switching the theme

### ISSUE THREAD

**Issue by danieldudzic** [woothemes/woosidebars#31]
It seems that the Widget Areas are not keeping the widgets in place after you switch the themes.

**Comment by mattyza** [comment]
@danieldudzic I've done some testing and, upon switching between themes, the widgets are set on a per-theme basis.

To reproduce:
- Activate TwentyFifteen and add the "Archive" and "Calendar" widgets to a custom widget area.
- Switch to TwentyFourteen. You'll see the widgets are now missing from the widget area.
- Add the "Categories" widget to the now-empty custom widget area.
- Switch back to TwentyFifteen.
- The "Archive" and "Calendar" widgets should now be present again in the custom widget area, instead of the "Categories" widget.
